-- SEFROU STORE: categories management migration
-- Reuses the existing public.categories table and products storage bucket.

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text,
    image text,
    description text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.categories add column if not exists slug text;
alter table public.categories add column if not exists description text;
alter table public.categories add column if not exists sort_order integer not null default 0;
alter table public.categories add column if not exists is_active boolean not null default true;
alter table public.categories add column if not exists created_at timestamptz not null default now();
alter table public.categories add column if not exists updated_at timestamptz not null default now();

update public.categories
set slug = coalesce(nullif(slug, ''), lower(regexp_replace(trim(name), '[^a-zA-Z0-9]+', '-', 'g'))),
    updated_at = now()
where slug is null or slug = '';

with ordered as (
    select id, row_number() over (order by id) - 1 as position
    from public.categories
)
update public.categories c
set sort_order = ordered.position
from ordered
where c.id = ordered.id and c.sort_order = 0;

create index if not exists categories_active_order_idx
on public.categories (is_active, sort_order, id);

alter table public.categories enable row level security;
grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;

drop policy if exists "visitors can read categories" on public.categories;
create policy "visitors can read active categories"
on public.categories for select to anon, authenticated
using (is_active = true or public.is_store_admin());

drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories"
on public.categories for all to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

drop policy if exists "admins manage category images" on storage.objects;
create policy "admins manage category images"
on storage.objects for all to authenticated
using (bucket_id = 'categories' and public.is_store_admin())
with check (bucket_id = 'categories' and public.is_store_admin());
